name = "${worker_name}"
main = "src/index.js"
compatibility_date = "${compatibility_date}"

# KV Namespace for storing heartbeat logs
# This file is automatically generated by Terraform
[[kv_namespaces]]
binding = "HEARTBEAT_LOGS"
id = "${kv_namespace_id}"

# Optional KV Namespace for ingest allowlist
[[kv_namespaces]]
binding = "INGEST_ALLOWLIST"
id = "${ingest_allowlist_namespace_id}"
preview_id = "${ingest_allowlist_namespace_preview_id}"

# Cron trigger - checks for stale heartbeats every 5 minutes
[triggers]
crons = ["*/5 * * * *"]

# Variables for configuration
[vars]
# Maximum number of log entries to keep per service
MAX_LOG_ENTRIES = "100"

